name: QuantumBenchmarkQIO
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - pip:
      - amazon-braket-ocean-plugin==1.0.5
      - amazon-braket-pennylane-plugin==1.5.2
      - dwave-ocean-sdk==6.4.1
      - qiskit==0.34.1
      - qiskit-optimization==0.3.2
      - azure-quantum==0.27.253010
      - azure-cli==2.43.0
      - quantagonia-api-client==0.49
      - boto3==1.26.23
      - scipy==1.10.0
      - httplib2==0.21.0
      - h5py==3.8.0
      - pandas==2.0.3
      - scikit-learn==1.3.0
      # - gurobipy=10.0.1  must use conda to install in order to get license tools
      # see https://support.gurobi.com/hc/en-us/articles/12872889819921
